name: Java Maven Build & Publish Artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Maven settings
        run: echo "MAVEN SETTINGS - > ${{ secrets.MAVEN_SETTINGS_PATH }}"
      - name: Build with Maven
        run: mvn clean install
      - name: Publish with Maven
        run: mvn deploy --settings ${{ secrets.MAVEN_SETTINGS_PATH }}

  sonarqube:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
      - name: Run SonarQube Scan
        run: |
          echo "SONAR URL - > ${{ secrets.SONAR_HOST_URL }}"
          mvn sonar:sonar \
            -Dsonar.projectKey=test-maven-project \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  publish-job:
    runs-on: ubuntu-latest
    needs: sonarqube
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: target/*.jar

